repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
    -   id: yapf
        args: [--in-place, --parallel, --recursive]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py312-plus]
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.2.2
    hooks:
    -   id: pylint
        name: pylint
        language: system
        types: [python]
        require_serial: false
        args: [--rcfile=pylint.rc, --jobs=0]
